name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: CodeNobility
          outputs: dist/snake.svg

      - name: Commit & Push
        run: |
          git config --global user.name "CodeNobility"
          git config --global user.email "you@example.com"
          git add dist/snake.svg
          git commit -m "update snake" || echo "no changes"
          git push
